name: Deploy NestJS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e

            echo "===== START DEPLOY ====="

            # Move to project folder
            cd /www/wwwroot/backend_live_chat_new || exit 1

            # Pull latest code
            git pull origin main


            # Install dependencies + build
            npm install
            npm run build

            # Ensure pm2 exists (IMPORTANT FIX)
            export PATH=$PATH:/www/server/nodejs/v20.17.0/bin

            # If pm2 not installed, install it
            if ! command -v pm2 &> /dev/null
            then
              echo "PM2 not found -> installing..."
              npm install -g pm2
            fi

            # Restart app
            pm2 delete backend_live_chat_new || true
            pm2 start dist/main.js --name backend_live_chat_new

            # Save process list
            pm2 save

            echo "===== DEPLOY DONE ====="