script: |
  set -e
  echo "===== START ====="

  cd /var/www/backend_live_chat_new || exit 1

  git pull origin main

  node -v
  npm -v

  npm install
  npm run build

  pm2 list || true

  pm2 delete nest-app || true
  pm2 start dist/main.js --name nest-app

  pm2 save

  echo "===== DONE ====="